default_stages: [commit]
repos:
  - repo: local
    hooks:
      - id: ggshield-local
        name: GitGuardian Shield
        entry: pipenv run ggshield secret scan pre-commit
        language: system
        types: [python]
        stages: [commit]

  - repo: local
    hooks:
      - id: ggshield-local
        name: GitGuardian Shield
        entry: pipenv run ggshield secret scan pre-push
        language: system
        pass_filenames: false
        types: [python]
        stages: [push]
