version: "3"
services:
  fastapi-server:
    build: app
    restart: on-failure
    entrypoint: ""
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload"]
    ports:
      - 8080:8000
      - 5678:5678
    volumes:
      - ./app:/code
    depends_on:
      - redis

  redis:
    image: redis:alpine
