version: '3'
services:
  fastapi-server:
    build: app
    command: '--host 0.0.0.0 --port 80 --reload'
    restart: on-failure
    ports:
      - 8080:80
      - 5678:5678
    volumes:
      - ./app:/code
    depends_on:
      - redis

  redis:
    image: redis:alpine
