# Book settings
title: machine-learning
author: Ron Medina
logo: img/loss_surface.png
exclude_patterns: []  # Patterns to skip when building the book. Can be glob-style (e.g. "*skip.ipynb")

execute:
  execute_notebooks: "off"

repository:
  url: https://github.com/particle1331/machine-learning-collection

latex:
  latex_documents:
    targetname: book.tex

html:
  extra_navbar: ""  # Will be displayed underneath the left navbar.
  use_repository_button: true
  favicon: "img/loss_surface.png"
  home_page_in_navbar: false
  baseurl: https://github.com/particle1331/machine-learning-collection

sphinx:
  extra_extensions:
   - sphinx_panels