[tool.pylint.messages_control]
max-line-length = 88
disable = [
  "missing-docstring",
  "unused-argument",
  "missing-class-docstring",
  "missing-function-docstring",
  "invalid-name",
]

[tool.black]
line-length = 88
target-version = ['py39']
skip-string-normalization = true
