[tool.pylint.messages_control]
max-line-length = 88
disable = [
  "missing-docstring",
  "unused-argument",
  "final-newline",
  "missing-class-docstring",
  "missing-function-docstring",
  "invalid-name",
]
