title: machine-learning
author: Ron Medina
logo: img/loss_surface.png

execute:
  execute_notebooks: "off"

latex:
  latex_documents:
    targetname: book.tex

bibtex_bibfiles:
  - references.bib

repository:
  url: https://github.com/particle1331/machine-learning-collection
  path_to_book: docs
  branch: master

html:
  use_issues_button: true
  use_binder_button: false
  use_repository_button: true
  home_page_in_navbar: false
  favicon: "img/loss_surface.png"

sphinx:
  extra_extensions:
   - sphinx_panels
  # config:
  #   html_theme: sphinx_material
  #   html_theme_options:
  #     color_primary: blue
  #     color_accent: light-blue
  #     globaltoc_depth: 3
  #     globaltoc_collapse: false
  #     globaltoc_includehidden: false