title: machine-learning
author: Ron Medina. Powered by <a href="https://jupyterbook.org">Jupyter Book</a>.
logo: img/loss_surface.png

execute:
  execute_notebooks: "off"

latex:
  latex_documents:
    targetname: book.tex

bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/particle1331/machine-learning-collection # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

html:
  home_page_in_navbar: false
  use_issues_button: true
  use_repository_button: true
  extra_navbar: ""
  favicon: "img/loss_surface.png"


# launch_buttons:
#   notebook_interface: jupyterlab

# sphinx:
#   config:
#     html_js_files:
#     - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js