title: "<b>𝙾𝙺 𝚃𝚛𝚊𝚗𝚜𝚏𝚘𝚛𝚖𝚎𝚛</b>"  
author: 𝗽𝗮𝗿𝘁𝗶𝗰𝗹𝗲𝟭𝟯𝟯𝟭. Powered by <a href="https://jupyterbook.org">Jupyter Book</a>.
logo: img/transformer-neural-network.jpeg

execute:
  execute_notebooks: 'off'

latex:
  latex_documents:
    targetname: book.tex

bibtex_bibfiles:
  - references.bib

launch_buttons:
  binderhub_url: ""
  
repository:
  url: https://github.com/particle1331/ok-transformer
  path_to_book: docs  # Path to book relative to repository root
  branch: master      # Branch of repo to use when creating links

html:
  home_page_in_navbar: false
  use_issues_button: true
  use_repository_button: true
  extra_navbar: ""
  favicon: "img/ok.png"

sphinx:
  config:
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js

only_build_toc_files: true
