name: build-jupyter-book

on:
  - push
  - pull_request

jobs:
  if: ${{ github.ref == 'refs/heads/master' }}
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.6']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      if: ${{ github.ref == 'refs/heads/master' }}
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions
    - name: Build Jupyter book with tox
      if: ${{ github.ref == 'refs/heads/master' }}
      run: tox -e buildbook
